services:
  json-to-eli:
    #build: ./
    image: semtech/mu-javascript-template:1.9.1
    restart: no
    labels:
      - logging=true
    environment:
      NODE_ENV: development
    ports:
      - "8082:80"
      - "9225:9229"
    volumes:
      - ./:/app
    networks:
      - debug

networks:
  debug:
    external: true
